version: "3.9"

services:
  web:
    build: .
    ports: 
      - "80:80"
    environment: 
      HOST: 0.0.0.0
      PORT: 80
      mongo_URL: mongo_URL=mongodb://host.docker.internal:27017/Golang
      JWT_TOKEN: someToeknToKeepInSecret
    
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
