version: "3.9"

services:
  web:
    build: ../
    ports: 
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
