name: Docker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
      mongo_URL: ${{ secrets.MONGO_URL }}
    steps: 
    - 
      name: Check out Repo
      uses: actions/checkout@v2

    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
    
    - 
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go-backend:latest

  test:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      mongo_URL: ${{ secrets.MONGO_URL }}
      JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Go unit testing
        run: |
          cd server 
          go build -o run-server
          ./run-server &
          go test
  


 
  deplyoment:
      runs-on: ubuntu-latest
      env:
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        mongo_URL: ${{ secrets.MONGO_URL }}
        JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      steps:
      -
        name: Check out Repo
        uses: actions/checkout@v2
     
      - 
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - 
        name: Terraform
        run: |
          cd terraform
          terraform fmt -check
          terraform init
          terraform validate -no-color
          terraform plan -no-color
          terraform apply -auto-approve


  