name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      mongo_URL: ${{ secrets.MONGO_URL }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd ./ci 
        docker-compose build 

  test:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      mongo_URL: mongodb://
    steps:
      - uses: actions/checkout@v2
      - name: Go unit testing
        run: |
          cd server 
          go test